version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-table_data:/var/lib/postgresql/data